#!/usr/bin/env python3
"""
扫描 Assets/Scripts 下所有 .cs 文件，发现所有 CComponent 子类，
生成 ComponentAccess.g.cs。

完全脱离 Unity 编译环境，仅依赖源文件文本解析。
用法: python generate_component_access.py
从项目根目录运行。
"""

import os
import re
import sys
from pathlib import Path

SCRIPTS_DIR = "Assets/Scripts"
OUTPUT_PATH = "Assets/Scripts/GamePlay/Util/Generated/ComponentAccess.g.cs"

# 匹配 namespace 声明
NS_RE = re.compile(r"namespace\s+([\w.]+)")

# 匹配 class 声明：非 abstract，直接继承 CComponent（不含泛型参数）
# 示例: public class UnitCombat : CComponent
# 示例: public sealed class Foo : ISome, CComponent
CLASS_RE = re.compile(
    r'(?:^|\n)\s*'
    r'(?:(?:public|internal|private|protected)\s+)?'
    r'(?:sealed\s+)?'
    r'(?:partial\s+)?'
    r'(?!abstract\s+)'
    r'class\s+(\w+)'
    r'(?:<[^>]*>)?\s*:\s*[^\{]*?\bCComponent\b',
    re.MULTILINE
)

HEADER = """\
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by generate_component_access.py.
// </auto-generated>
//------------------------------------------------------------------------------
using Core.Capability;
namespace GamePlay.Util
{
    public static class ComponentAccess
    {
"""

FOOTER = """\
    }
}
"""


def find_cs_files(scripts_dir: str):
    """返回 scripts_dir 下所有非 Editor 目录的 .cs 文件路径。"""
    files = []
    for root, dirs, filenames in os.walk(scripts_dir):
        # 跳过 Editor 目录和 ~ 后缀目录（Unity 忽略 Unity 包内的 ~ 目录）
        dirs[:] = [d for d in dirs if d != "Editor" and not d.endswith("~")]
        rel_root = root.replace("\\", "/")
        if "/Editor/" in rel_root:
            continue
        for f in filenames:
            if f.endswith(".cs"):
                files.append(os.path.join(root, f))
    return files


def parse_file(filepath: str) -> list[str]:
    """解析单个 .cs 文件，返回其中所有 CComponent 子类的完整类型名列表。"""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
    except Exception:
        return []

    result = []
    ns_matches = list(NS_RE.finditer(content))

    if not ns_matches:
        # 无 namespace 的全局类
        result.extend(_find_classes(content, ""))
        return result

    for i, m in enumerate(ns_matches):
        ns = m.group(1)
        # 跳过 Editor 命名空间
        if ".Editor" in ns or ns.startswith("UnityEditor"):
            continue

        block_start = m.start()
        block_end = ns_matches[i + 1].start() if i + 1 < len(ns_matches) else len(content)
        block_text = content[block_start:block_end]

        for class_match in CLASS_RE.finditer(block_text):
            class_name = class_match.group(1)
            full_name = f"{ns}.{class_name}"
            result.append(full_name)

    return result


def _find_classes(text: str, ns: str) -> list[str]:
    result = []
    for m in CLASS_RE.finditer(text):
        class_name = m.group(1)
        full_name = f"{ns}.{class_name}" if ns else class_name
        result.append(full_name)
    return result


def fullname_to_parts(fullname: str) -> tuple[str, str]:
    """返回 (simple_name, full_type_name_for_code)。"""
    return fullname.rsplit(".", 1)[-1], fullname


def assign_aliases(components: list[str]) -> dict[str, tuple[str, str]]:
    """
    输入: 完整类型名列表
    输出: {alias: (fullname_for_code, simple_name)}
    """
    alias_map = {}
    groups: dict[str, list[str]] = {}
    for fn in components:
        sn = fn.rsplit(".", 1)[-1]
        groups.setdefault(sn, []).append(fn)

    used = set()
    for sn, names in sorted(groups.items()):
        for fn in names:
            if len(names) == 1:
                alias = _sanitize(sn)
            else:
                alias = _sanitize(fn.replace(".", "_").replace("+", "_"))
            if alias in used:
                suffix = 2
                while f"{alias}_{suffix}" in used:
                    suffix += 1
                alias = f"{alias}_{suffix}"
            used.add(alias)
            alias_map[alias] = (fn, sn)
    return alias_map


def _sanitize(s: str) -> str:
    if not s:
        return "UnknownComponent"
    result = "".join(c if c.isalnum() or c == "_" else "_" for c in s)
    if not result or not (result[0].isalpha() or result[0] == "_"):
        result = "_" + result
    return result


def generate(files: list[str]) -> str:
    """生成 ComponentAccess.g.cs 的完整内容。"""
    collected = set()
    for fp in files:
        for name in parse_file(fp):
            collected.add(name)

    # CComponent 自身不继承 CComponent，但框架需要它的访问器，手动加入。
    collected.add("Core.Capability.CComponent")

    components = sorted(collected)
    alias_map = assign_aliases(components)

    lines = [HEADER]

    # ID 声明
    for alias, (fullname, _) in alias_map.items():
        lines.append(f"        public static readonly int {alias}Id = Component<{fullname}>.TId;")

    lines.append("")
    lines.append(f"        public static int Count => {len(components)};")
    lines.append("")

    # 每个组件的访问方法
    for i, (alias, (fullname, _)) in enumerate(alias_map.items()):
        lines.append(f"        public static bool Has{alias}(this CEntity entity)")
        lines.append("        {")
        lines.append(f"            return entity != null && entity.HasComponent({alias}Id);")
        lines.append("        }")
        lines.append("")

        lines.append(f"        public static bool TryGet{alias}(this CEntity entity, out {fullname} component)")
        lines.append("        {")
        lines.append("            component = null;")
        lines.append(f"            return entity != null && entity.TryGetComponent({alias}Id, out component);")
        lines.append("        }")
        lines.append("")

        lines.append(f"        public static {fullname} Get{alias}OrNull(this CEntity entity)")
        lines.append("        {")
        lines.append(f"            return entity != null ? entity.GetComponent({alias}Id) as {fullname} : null;")
        lines.append("        }")
        lines.append("")

        # 所有组件默认生成 Add 方法（Python 脚本无法判断是否有无参构造函数）
        lines.append(f"        public static {fullname} Add{alias}(this CEntity entity)")
        lines.append("        {")
        lines.append(f"            return entity != null ? entity.AddComponent<{fullname}>() : null;")
        lines.append("        }")
        lines.append("")

        lines.append(f"        public static bool Remove{alias}(this CEntity entity)")
        lines.append("        {")
        lines.append(f"            if (entity == null || !entity.HasComponent({alias}Id))")
        lines.append("            {")
        lines.append("                return false;")
        lines.append("            }")
        lines.append("")
        lines.append(f"            entity.RemoveComponent({alias}Id);")
        lines.append("            return true;")
        lines.append("        }")

        if i < len(components) - 1:
            lines.append("")

    lines.append(FOOTER)
    return "\n".join(lines) + "\n"


def main():
    project_root = Path(__file__).resolve().parent.parent
    scripts_dir = str(project_root / SCRIPTS_DIR)
    output_path = str(project_root / OUTPUT_PATH)

    if not os.path.isdir(scripts_dir):
        print(f"[ERROR] 找不到脚本目录: {scripts_dir}", file=sys.stderr)
        sys.exit(1)

    print(f"[ComponentAccess] 扫描目录: {scripts_dir}")
    files = find_cs_files(scripts_dir)
    print(f"[ComponentAccess] 找到 {len(files)} 个 .cs 文件")

    content = generate(files)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)

    # 统计组件数
    component_count = content.count("public static readonly int") - content.count("Count =>")
    # 更准确的方式
    component_count = content.count("Id = Component<")
    print(f"[ComponentAccess] 生成完成: {output_path} (共 {component_count} 个组件)")


if __name__ == "__main__":
    main()
