#!/usr/bin/env python3
"""
扫描 Assets/Scripts 下所有 .cs 文件，发现所有 CapabilityBase 子类，
解析其 TickGroupOrder 并依序生成 AllCapability.g.cs。

完全脱离 Unity 编译环境，仅依赖源文件文本解析。
用法: python generate_all_capability.py
从项目根目录运行。
"""

import os
import re
import sys
from pathlib import Path

SCRIPTS_DIR = "Assets/Scripts"
CAPABILITY_ORDER_PATH = "Assets/Scripts/GamePlay/World/CapabilityOrder.cs"
OUTPUT_PATH = "Assets/Scripts/GamePlay/Util/Generated/AllCapability.g.cs"

# 匹配 namespace
NS_RE = re.compile(r"namespace\s+([\w.]+)")

# 匹配 class X : CapabilityBase（非 abstract，无泛型参数）
CAP_CLASS_RE = re.compile(
    r'(?:^|\n)\s*'
    r'(?:(?:public|internal|private|protected)\s+)?'
    r'(?:sealed\s+)?'
    r'(?:partial\s+)?'
    r'(?!abstract\s+)'
    r'class\s+(\w+)'
    r'(?:<[^>]*>)?\s*:\s*[^\{]*?\bCapabilityBase\b',
    re.MULTILINE
)

# 匹配 TickGroupOrder 赋值表达式
TGO_RE = re.compile(
    r'public\s+override\s+int\s+TickGroupOrder\s*\{[^}]*\}\s*=\s*(.+?);',
    re.DOTALL
)

HEADER = """\
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by generate_all_capability.py.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Core.Capability
{
    public static class AllCapability
    {
        public static readonly int TotalCapabilities = Order();

        public static void Register(CapabilityWorld world)
        {
            if (world == null)
            {
                return;
            }
{register_lines}
        }

        private static int Order()
        {
"""

FOOTER = """\
            return {count};
        }}
    }}
}}
"""


def parse_capability_order(filepath: str) -> dict[str, int]:
    """
    解析 CapabilityOrder.cs，返回 {常量名: int值} 字典。
    """
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
    except Exception:
        return {}

    constants: dict[str, int] = {}
    # 匹配 const int X = Y; 或 public const int X = Y;
    const_re = re.compile(r"(?:public\s+|private\s+|internal\s+)?const\s+int\s+(\w+)\s*=\s*(.+?)\s*;")

    # 第一遍：提取所有赋值表达式
    raw: dict[str, str] = {}
    for m in const_re.finditer(content):
        name = m.group(1)
        expr = m.group(2).strip()
        raw[name] = expr

    # 解析表达式为 int 值
    def resolve(expr: str, depth: int = 0) -> int | None:
        if depth > 20:
            return None
        expr = expr.strip()
        # 字面量
        try:
            return int(expr)
        except ValueError:
            pass
        # 简单引用
        if expr in constants:
            return constants[expr]
        # X + Y 或 X - Y
        for op, fn in [("+", lambda a, b: a + b), ("-", lambda a, b: a - b)]:
            parts = expr.split(op, 1)
            if len(parts) == 2:
                a = resolve(parts[0].strip(), depth + 1)
                b = resolve(parts[1].strip(), depth + 1)
                if a is not None and b is not None:
                    return fn(a, b)
                return None
        # 再尝试作为未解析的引用
        if expr in raw and expr not in constants and depth == 0:
            raw_val = raw[expr]
            val = resolve(raw_val, depth + 1)
            if val is not None:
                constants[expr] = val
                return val
        return None

    for name, expr in raw.items():
        val = resolve(expr)
        if val is not None:
            constants[name] = val

    return constants


def parse_tick_group_order(class_text: str, order_map: dict[str, int]) -> int:
    """从类文本中提取 TickGroupOrder 的值。"""
    m = TGO_RE.search(class_text)
    if not m:
        return 0  # 默认 CapabilityBase.TickGroupOrder = 0

    expr = m.group(1).strip()

    # 尝试直接在 order_map 中查找
    if expr in order_map:
        return order_map[expr]

    # 尝试解析 CapabilityOrder.Xxx 形式
    if expr.startswith("CapabilityOrder."):
        # 简单常量引用：CapabilityOrder.StageResolve
        const_name = expr[len("CapabilityOrder."):].strip()
        if const_name in order_map:
            return order_map[const_name]

        # 算术表达式：CapabilityOrder.StageResolve + 20
        # 先把所有 CapabilityOrder. 前缀去掉，再用已知常量替换
        naked = expr.replace("CapabilityOrder.", "")
        resolved = _replace_constants(naked, order_map)
        val = _safe_eval(resolved)
        if val is not None:
            return val

    # int.MaxValue 特殊处理
    if expr == "int.MaxValue":
        return 2147483647

    # 其他可能的常量组合表达式
    resolved = _replace_constants(expr, order_map)
    val = _safe_eval(resolved)
    if val is not None:
        return val

    return 0


def _replace_constants(expr: str, order_map: dict[str, int]) -> str:
    """将表达式中的 CapabilityOrder 常量名替换为数值，长名优先避免部分匹配。"""
    resolved = expr
    for name, val in sorted(order_map.items(), key=lambda x: -len(x[0])):
        resolved = resolved.replace(name, str(val))
    return resolved


def _safe_eval(expr: str) -> int | None:
    """安全求值纯整数算术表达式，允许 + - * / () 和十进制数字。"""
    import ast
    import operator
    try:
        node = ast.parse(expr.strip(), mode="eval")
    except SyntaxError:
        return None

    allowed_nodes = (ast.Expression, ast.Constant,
                     ast.BinOp, ast.UnaryOp, ast.Add, ast.Sub,
                     ast.Mult, ast.Div, ast.USub, ast.UAdd)

    for n in ast.walk(node):
        if isinstance(n, ast.Constant):
            if not isinstance(n.value, (int, float)):
                return None
        elif not isinstance(n, allowed_nodes):
            return None

    try:
        return int(eval(compile(node, "<expr>", "eval"), {"__builtins__": {}}, {}))
    except Exception:
        return None


def find_cs_files(scripts_dir: str) -> list[str]:
    """返回 scripts_dir 下所有非 Editor 的 .cs 文件路径。"""
    files = []
    for root, dirs, filenames in os.walk(scripts_dir):
        # 跳过 Editor 目录和 ~ 后缀目录（Unity 惯例忽略）
        dirs[:] = [d for d in dirs if d != "Editor" and not d.endswith("~")]
        rel_root = root.replace("\\", "/")
        if "/Editor/" in rel_root:
            continue
        for f in filenames:
            if f.endswith(".cs"):
                files.append(os.path.join(root, f))
    return files


def parse_file(filepath: str) -> list[tuple[str, str, int]]:
    """
    解析 .cs 文件，返回 [(fullName, className, tickGroupOrder), ...]。
    """
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
    except Exception:
        return []

    result = []
    ns_matches = list(NS_RE.finditer(content))

    if not ns_matches:
        result.extend(_find_caps(content, ""))
        return result

    for i, m in enumerate(ns_matches):
        ns = m.group(1)
        if ".Editor" in ns or ns.startswith("UnityEditor"):
            continue

        block_start = m.start()
        block_end = ns_matches[i + 1].start() if i + 1 < len(ns_matches) else len(content)
        block_text = content[block_start:block_end]
        result.extend(_find_caps(block_text, ns))

    return result


def _find_caps(text: str, ns: str) -> list[tuple[str, str, int]]:
    result = []
    for m in CAP_CLASS_RE.finditer(text):
        class_name = m.group(1)
        full_name = f"{ns}.{class_name}" if ns else class_name

        # 找到该 class 的完整代码块（从 class 开始到匹配的花括号结束）
        class_start = m.start()
        # 找到匹配的 { }
        brace_start = text.find("{", m.end())
        if brace_start < 0:
            continue
        depth = 1
        i = brace_start + 1
        while i < len(text) and depth > 0:
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
            i += 1
        class_text = text[m.start():i]
        result.append((full_name, class_name, class_text))

    return result


def generate(files: list[str], order_map: dict[str, int]) -> str:
    collected = []
    invalid = []
    for fp in files:
        for full_name, class_name, class_text in parse_file(fp):
            if not class_name.startswith("Cp"):
                invalid.append(f"{full_name} ({fp})")
                continue
            tgo = parse_tick_group_order(class_text, order_map)
            collected.append((full_name, tgo))

    if invalid:
        details = "\n".join(f"  - {item}" for item in invalid)
        raise RuntimeError(
            "发现非 Cp 前缀的 CapabilityBase 子类，请先重命名：\n" + details
        )

    # 按 TickGroupOrder 排序，相同则按全名排序
    collected.sort(key=lambda x: (x[1], x[0]))

    register_lines = [
        f"            world.BindGlobalCapability<{full_name}>();"
        for full_name, _ in collected
    ]

    lines = [HEADER.replace("{register_lines}", "\n".join(register_lines))]
    for i, (full_name, _) in enumerate(collected):
        prefix = "            var orderTid = " if i == 0 else "            orderTid = "
        lines.append(
            f"{prefix}CapabilityId<{full_name}, IUpdateSystem>.TId;"
        )

    lines.append(FOOTER.format(count=len(collected)))
    return "\n".join(lines) + "\n"


def main():
    project_root = Path(__file__).resolve().parent.parent
    scripts_dir = str(project_root / SCRIPTS_DIR)
    cap_order_path = str(project_root / CAPABILITY_ORDER_PATH)
    output_path = str(project_root / OUTPUT_PATH)

    if not os.path.isdir(scripts_dir):
        print(f"[ERROR] 找不到脚本目录: {scripts_dir}", file=sys.stderr)
        sys.exit(1)

    print(f"[AllCapability] 解析 CapabilityOrder: {cap_order_path}")
    order_map = parse_capability_order(cap_order_path)
    print(f"[AllCapability] 解析到 {len(order_map)} 个常量")

    print(f"[AllCapability] 扫描目录: {scripts_dir}")
    files = find_cs_files(scripts_dir)
    print(f"[AllCapability] 找到 {len(files)} 个 .cs 文件")

    content = generate(files, order_map)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)

    cap_count = content.count("CapabilityId<")
    print(f"[AllCapability] 生成完成: {output_path} (共 {cap_count} 个能力)")


if __name__ == "__main__":
    main()
