#region

using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEngine;
using Object = UnityEngine.Object;

#endregion

namespace Core.Capability.Editor
{
    public static class CapabilityCodeGenerator
    {
        private const string MenuGeneratePath = "框架工具/代码生成/生成 AllCapability";

        private const string MenuOpenGeneratedPath = "框架工具/代码生成/打开 AllCapability 输出文件";

        private const string TemplateAssetPath =
            "Assets/Scripts/Core/Capability/Editor/CodeGen/Templates/AllCapability.Template.txt";

        private const string OutputAssetPath =
            "Assets/Scripts/GamePlay/Util/Generated/AllCapability.g.cs";

        private const string FallbackTemplate =
            "//------------------------------------------------------------------------------\n" +
            "// <auto-generated>\n" +
            "//     This code was generated by CapabilityCodeGenerator.\n" +
            "// </auto-generated>\n" +
            "//------------------------------------------------------------------------------\n" +
            "namespace GamePlay.Util\n" +
            "{\n" +
            "    public static class AllCapability\n" +
            "    {\n" +
            "        public static readonly int TotalCapabilities = Order();\n" +
            "\n" +
            "        public static readonly int TotallCapabiltys = TotalCapabilities;\n" +
            "\n" +
            "        private static int Order()\n" +
            "        {\n" +
            "{0}\n" +
            "            return {1};\n" +
            "        }\n" +
            "    }\n" +
            "}\n";

        [MenuItem(MenuGeneratePath, false, 20)]
        public static void GenerateAllCapability()
        {
            if (EditorApplication.isPlaying)
            {
                Debug.LogWarning("[CapabilityCodeGenerator] Play Mode 下不能执行代码生成。");
                return;
            }

            try
            {
                List<CapabilityMetadata> metadata = CollectCapabilities();
                metadata.Sort(CompareCapabilityMetadata);

                string template = LoadTemplate();
                string orderLines = BuildOrderLines(metadata);
                string content = ApplyTemplate(template, orderLines, metadata.Count);

                string outputFullPath = Path.GetFullPath(OutputAssetPath);
                string outputDirectory = Path.GetDirectoryName(outputFullPath);
                if (!string.IsNullOrWhiteSpace(outputDirectory) &&
                    !Directory.Exists(outputDirectory))
                {
                    if (outputDirectory != null)
                    {
                        Directory.CreateDirectory(outputDirectory);
                    }
                }

                File.WriteAllText(outputFullPath, content, Encoding.UTF8);
                AssetDatabase.Refresh();

                Debug.Log(
                    $"[CapabilityCodeGenerator] 生成完成: {OutputAssetPath} (共 {metadata.Count} 个 Capability)。");
            }
            catch (Exception exception)
            {
                Debug.LogError($"[CapabilityCodeGenerator] 生成失败: {exception}");
            }
        }

        /*[MenuItem(LegacyMenuGeneratePath, false, 2)]
        public static void GenerateAllCapabilityLegacyMenu()
        {
            GenerateAllCapability();
        }*/

        [MenuItem(MenuOpenGeneratedPath, false, 21)]
        public static void OpenGeneratedFile()
        {
            Object asset = AssetDatabase.LoadAssetAtPath<Object>(OutputAssetPath);
            if (asset == null)
            {
                Debug.LogWarning($"[CapabilityCodeGenerator] 输出文件不存在: {OutputAssetPath}");
                return;
            }

            AssetDatabase.OpenAsset(asset);
        }

        private static string LoadTemplate()
        {
            TextAsset templateAsset = AssetDatabase.LoadAssetAtPath<TextAsset>(TemplateAssetPath);
            if (templateAsset != null && !string.IsNullOrWhiteSpace(templateAsset.text))
            {
                return templateAsset.text;
            }

            return FallbackTemplate;
        }

        private static string ApplyTemplate(string template, string orderLines, int capabilityCount)
        {
            string content = template.Replace("{0}", orderLines);
            content = content.Replace("{1}", capabilityCount.ToString());
            return content;
        }

        private static List<CapabilityMetadata> CollectCapabilities()
        {
            List<CapabilityMetadata> metadata = new List<CapabilityMetadata>(64);
            HashSet<Type> capabilityTypes = new HashSet<Type>();
            Assembly[] assemblies = AppDomain.CurrentDomain.GetAssemblies();
            for (int i = 0; i < assemblies.Length; i++)
            {
                Assembly assembly = assemblies[i];
                Type[] types = GetTypesSafely(assembly);
                for (int j = 0; j < types.Length; j++)
                {
                    Type type = types[j];
                    if (type == null || !type.IsClass || type.IsAbstract)
                    {
                        continue;
                    }

                    if (type.ContainsGenericParameters)
                    {
                        continue;
                    }

                    if (!typeof(CapabilityBase).IsAssignableFrom(type))
                    {
                        continue;
                    }

                    if (!capabilityTypes.Add(type))
                    {
                        continue;
                    }

                    if (!TryCreateCapabilityMetadata(type,
                            out CapabilityMetadata capabilityMetadata))
                    {
                        continue;
                    }

                    metadata.Add(capabilityMetadata);
                }
            }

            return metadata;
        }

        private static Type[] GetTypesSafely(Assembly assembly)
        {
            try
            {
                return assembly.GetTypes();
            }
            catch (ReflectionTypeLoadException exception)
            {
                return exception.Types;
            }
        }

        private static bool TryCreateCapabilityMetadata(Type type, out CapabilityMetadata metadata)
        {
            metadata = default;

            CapabilityBase instance;
            try
            {
                instance = Activator.CreateInstance(type) as CapabilityBase;
            }
            catch (Exception exception)
            {
                Debug.LogWarning(
                    $"[CapabilityCodeGenerator] 跳过 {type.FullName}，无法实例化: {exception.Message}");
                return false;
            }

            if (instance == null)
            {
                return false;
            }

            metadata = new CapabilityMetadata
            {
                Type = type,
                TickGroupOrder = instance.TickGroupOrder,
                UpdateMode = instance.UpdateMode
            };

            instance.Dispose();
            return true;
        }

        private static int CompareCapabilityMetadata
            (CapabilityMetadata left, CapabilityMetadata right)
        {
            int byTick = left.TickGroupOrder.CompareTo(right.TickGroupOrder);
            if (byTick != 0)
            {
                return byTick;
            }

            return string.CompareOrdinal(left.Type.FullName, right.Type.FullName);
        }

        private static string BuildOrderLines(List<CapabilityMetadata> metadata)
        {
            if (metadata.Count == 0)
            {
                return "            var orderTid = 0;";
            }

            StringBuilder builder = new StringBuilder(256);
            for (int i = 0; i < metadata.Count; i++)
            {
                CapabilityMetadata item = metadata[i];
                string updateInterface = item.UpdateMode == CapabilityUpdateMode.FixedUpdate
                    ? nameof(IFixedUpdateSystem)
                    : nameof(IUpdateSystem);
                string linePrefix =
                    i == 0 ? "            var orderTid = " : "            orderTid = ";
                builder.Append(linePrefix);
                builder.Append("CapabilityId<");
                builder.Append(GetTypeName(item.Type));
                builder.Append(", ");
                builder.Append(updateInterface);
                builder.Append(">.TId;");
                if (i < metadata.Count - 1)
                {
                    builder.AppendLine();
                }
            }

            return builder.ToString();
        }

        private static string GetTypeName(Type type)
        {
            if (!type.IsGenericType)
            {
                return (type.FullName ?? type.Name).Replace('+', '.');
            }

            string typeName = type.GetGenericTypeDefinition().FullName;
            if (string.IsNullOrWhiteSpace(typeName))
            {
                typeName = type.Name;
            }

            if (typeName == null)
            {
                Debug.LogWarning($"[CapabilityCodeGenerator] 跳过 {type.FullName}，无法获取泛型定义");
                return type.Name;
            }

            int tickIndex = typeName.IndexOf('`');
            if (tickIndex >= 0)
            {
                typeName = typeName.Substring(0, tickIndex);
            }

            Type[] arguments = type.GetGenericArguments();
            StringBuilder builder = new StringBuilder(typeName.Length + arguments.Length * 12);
            builder.Append(typeName.Replace('+', '.'));
            builder.Append('<');
            for (int i = 0; i < arguments.Length; i++)
            {
                if (i > 0)
                {
                    builder.Append(", ");
                }

                builder.Append(GetTypeName(arguments[i]));
            }

            builder.Append('>');
            return builder.ToString();
        }

        private struct CapabilityMetadata
        {
            public Type Type;

            public int TickGroupOrder;

            public CapabilityUpdateMode UpdateMode;
        }
    }
}